spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
  batch:
    jdbc:
      initialize-schema: embedded


---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/springbatch?useUnicode=true&characterEncoding=utf8
      username: root
      password: 1111
      driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    jdbc:
#      schema 생성과 관련한 option
      initialize-schema: always
#      기본은 BATCH_ , -> prefix를 바꾸게 되면 아래 이름으로 query가 생성이 됨.
#      query가 생성이 되는 것이지, table 이름도 변경이 되서 생성이 되는 것은 아니기 때문에 TABLE 이름도 변경해서 생성해 줘야한다.
      table-prefix: SYSTEM_
    job:
#    자동 실행 방지 enabled = false
#      enabled: false
#    job을 선별해서 실행하고자 할 때 names 설정 추가
#    NONE은 임의의 문자를 의미한다. {job.name:NONE} 실행시점에 argument로 받겠다는 의미임
#      names: batchJob2
      names: ${job.name:NONE}